@host = http://localhost:8000

### List matches
GET {{host}}/matches?limit=10
Content-Type: application/json

### Create match
POST {{host}}/matches
Content-Type: application/json

{
  "sport": "football",
  "homeTeam": "Team A",
  "awayTeam": "Team B",
  "startTime": "2026-06-27T18:00:00.000Z",
  "endTime": "2026-06-27T19:00:00.000Z",
  "homeScore": 0,
  "awayScore": 0
}

### List match comentaries
GET {{host}}/matches/1/commentary
Content-Type: application/json

### Create match commentary
POST {{host}}/matches/1/commentary
Content-Type: application/json

{
  "minute": 15,
  "sequence": 1,
  "period": "2nd half",
  "eventType": "goal",
  "actor": "Player A",
  "team": "Team A",
  "message": "Player A scored a goal!",
  "metadata": {
    "assist": "Player B"
  },
  "tags": ["goal", "teamA"]
}